version: '2'
services:
  ynu-hr-api:
    build: .
    ports:
      - "50071:3000"
    restart: always
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

